

all:


include ../../../src/kaldi.mk

CXXFLAGS += -I../../../src

TESTFILES =

OBJFILES = math-utils.o

LIBNAME = kaldi-vvutil

ADDLIBS = ../../../src/base/kaldi-base.a

include ../../../src/makefiles/default_rules.mk

