
all:
EXTRA_CXXFLAGS = -Wno-sign-compare
include ../../../src/kaldi.mk

CXXFLAGS += -I../../../src

BINFILES = math-test


OBJFILES =

ADDLIBS = ../vvutil/kaldi-vvutil.a ../../../src/base/kaldi-base.a


TESTFILES =

include ../../../src/makefiles/default_rules.mk
