#!/usr/bin/env python
#Copyright 2016  Tsinghua University (Author:Zhiyuan Tang).  Apache 2.0.

#This script accepts a Chinese stream and inserts blanks between Chinese characters,
#with English word as a character.
#Used to prepare character-based transcriptions and compute CER.

from __future__ import print_function
import sys, re

for l in sys.stdin:
  l=l.strip()
  ll=l.split()
  lk=ll[0]
  for v in ll[1:]:
    v = v.decode('utf-8')
    if ( re.match('\w', v) or v == '!SIL' ) and (not re.match('[0-9]', v[0])):
      lk= lk + ' ' + v
#    else:
#      for i in v:
#        lk= lk + ' ' + i
  print(lk.encode('utf-8'))
